### ISSUE TITLE
can't upload images

### ISSUE THREAD

**Issue by johan12** [2b3ez/FileManager4TinyMCE#13]
I just downloaded FileManager4TinyMCE and somehow I can't upload images. The uploading seems to go ok, but when I press 'return to files list' no images are shown.

I suppose it is a problem with my config.php.
Right now the code is:
$base_url="http://mydomain.com"; //url base of site if you want only relative url leave empty
$upload_dir = '/algerhof/img/'; // path from base_url to upload base dir
$current_path = '../../../../../../img/'; // relative path from filemanager folder to upload files folder

filemanager folder: 'http://mydomain.com/algerhof/admin/tinymce/js/tinymce/plugins/filemanager/'
images folder: 'http://mydomain.com/algerhof/img/'

I tried adding and removing some '../' from $current_path, but it won't help.

**Comment by johan12** [comment]
I think it's a problem with $root.
When I leave $root empty and make $upload_dir a relative path it does work. The only thing that doesn't work then is the feedback url to tinymce, that's also the relative path.
If I make $upload_dir static, no images are displayed.
If I use $root = rtrim($_SERVER['DOCUMENT_ROOT'],'/'); then $root is '/home/vhosts/mydomain.com/httpdocs'
I don't know if that's how it's supposed to be?

Anyhow, is there some other way to give the right feedback to tinymce, or to adjust the url variables?

**Comment by johan12** [comment]
I finally got it working. Still don't know what I did wrong, but I changed some of the folders and now it works.
The code I'm currently using:
$root = rtrim($_SERVER['DOCUMENT_ROOT'],'/');  // don't touch this configuration
$base_url=""; //url base of site if you want only relative url leave empty
$upload_dir = '/algerhof/files/'; // path from base_url to upload base dir
$current_path = '../../../../files/'; // relative path from filemanager folder to upload files folder

filemanager folder: 'http://mydomain.com/algerhof/admin/tinymce/plugins/filemanager/'
images folder: 'http://mydomain.com/algerhof/files/'

**Comment by trippo** [comment]
:)
