### ISSUE TITLE
FileManager usage for stand-alone?

### ISSUE THREAD

**Issue by Tomgroot** [2b3ez/FileManager4TinyMCE#14]
Has this FileManager also the option for stand-alone. In other words can I also use this outside TinyMce?

**Comment by Keeo** [comment]
I am looking for this feature too

**Comment by umefarooq** [comment]
hi i really like this plugin i have integreat with Codeigniter, look and feel is same but uploading and resizing is happening in Codeigniter

**Comment by andrnag** [comment]
umefarooq, hi! Could you contribute?

**Comment by umefarooq** [comment]
andrnag will share, let me setup git for it.

**Comment by ADmad** [comment]
I quite like the UI of this plugin. As others requested would be nice to be able to use it standalone too. May I suggest  checking out how [KCFinder](http://kcfinder.sunhater.com/) manages using it's filemanager in various modes.

Also it would be nice if the various configs of the filemanager can be handled through session vars like it can be done for KCFinder. This makes user authentication / authorization much simpler plus allows changing the  upload paths per user.

**Comment by trippo** [comment]
i return from holiday :) what do you want?

**Comment by ADmad** [comment]
@trippo Are you working on this feature request? :smile:

**Comment by trippo** [comment]
there is an user who is working in this (Dániel Kemény). 
if he fails in the next 2 week i implement this functionality because isn't hard

**Comment by ADmad** [comment]
Ok, good to know. Did you close the issue by mistake? It's still open :)

**Comment by trippo** [comment]
I update the plugin :) now your request is included

**Comment by ADmad** [comment]
@trippo Thanks I will check it out. The second part of my request still seems pending though: being able to manage config values like upload directory and access control to the filemanager through session :smile:

**Comment by trippo** [comment]
What do you mean? you can give me some examples?
