### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by enricopalazzo** [2b3ez/FileManager4TinyMCE#15]
Hi, 
I'm getting this error when trying to upload a file. 
I get the uploading animation, but I get a red X and this message. 

"403 Forbidden: You don't have permission to access /some_folder/assets/js/tinymce/plugins/filemanager/upload.php" 

I can access the upload.php file directly via browser with no permission error.
And I'm sure all my directory permissions are as they are suppossed to be. 

As a matter of fact, this same configuration works on my localhost, this only happens on the remote server. 

I've pinned down the issue to somewhere between the dropzone plugin, and the upload.php script,  but it's very hard to debug, and I can't seem to find any documentation of a similar problem. 

I tried changing some parameters on Dropzone, mainly the method, from POST to GET,  and then I get the green check, and no error, but the files are not being uploaded to the server. 

Any clues?

**Comment by jprogertest** [comment]
I got exactly the same problem, did you find a solution ?

**Comment by enricopalazzo** [comment]
Hi, 
Because of time constraints, I had to go back to Tinymce 3 and use a tried and proven working file manager library (PDW file browser). It's uglier, and less "intuitive" for end users, but it works. 

None the less, I pinned down the problem to a server issue with the Dropzone plugin. 

This is the answer I got at Dropzone github page:

https://github.com/enyo/dropzone/issues/184

I didn't try any of this yet. But if I can't make this work on a pretty standard server configuration (Greengeeks), without hacking the code, then I'll have to wait for a better library or make my own TinyMce 4 compatible one.

I hope you make it work, because this is a beautiful library. 
I was going to remove the use of Dropzone, and use a standard form, but as I said, because of the deadline I just went to my old working libraries.

**Comment by arndta** [comment]
Not any attempt to start an argument, but this plugin has worked fine for
many other people, also with standard hosting setups.

I suggest you follow enyo's advice and pinpoint your actual problem.
 Posting the solution here and on the dropzone thread would be helpful for
others also.

**Comment by enricopalazzo** [comment]
I'm planning on trying it again and follow enyo's suggestion when I have a chance.
I just don't have time on this project to go deeper on this issue.

As I said, I think this is a beautiful plugin and it worked perfectly on my local server and a development server, but at least now I know  there is an issue between dropzone and some servers settings

If I find a fix of course I'll post results.

**Comment by trippo** [comment]
I think is server configuration problem.

**Comment by FritzTGreen** [comment]
FYI - We were getting the same 403 Forbidden errors on both the upload.php and dialog.php files (depending upon my Dropzone forceFallback setting).

In the end, the problem was simply a misconfiguration of the paths in our /filemanager/config/config.php file. One of our programmers had added the path to the filemanager directory to the end of the $base_url, despite the fact that the comment at the end of the config line says "DON'T TOUCH (base url (only domain) of site (without final /))."

There may be other possible causes for like errors, but this is something to definitely check. After resetting the base_url to the default value, the errors went away and everything works great.

**Comment by sangnguyendev** [comment]
Oh wow, tks @FritzTGreen it's help full

**Comment by trippo** [comment]
Please use responsive filemanager at http://responsivefilemanager.com

**Comment by advacom** [comment]
I've found a solution to the 403. In my case the hosting companies firewall was blocking the uploads. Try check with your host.
