### ISSUE TITLE
dropzone fallback

### ISSUE THREAD

**Issue by johan12** [2b3ez/FileManager4TinyMCE#19]
On some browsers the dropzone isn't supported. Therefore dropzone has a fallback, so you can upload with a browse button. The problem is that there is no submit button, so you can't upload the file. 

Any solutions?

**Comment by johan12** [comment]
<p>I saw this fix:<br />
  -  &lt;form id=&quot;myAwesomeDropzone&quot; class=&quot;dropzone&quot;&gt;<br />
  +  &lt;form action=&quot;upload.php&quot; id=&quot;myAwesomeDropzone&quot; class=&quot;dropzone&quot;&gt;<br />
  but it didn't work, the problem is that you have to get back to dialog.php, so I came up with the following fix:<br />
  - include 'config.php';<br />
  - include('utils.php');<br />
  + if(isset($_POST['submit'])){<br />
  + include('upload.php');<br />
  + }<br />
  + else{<br />
  + include 'config.php';<br />
  + include('utils.php');<br />
  + }</p>

<p>...............</p>

<p>- &lt;form action=&quot;upload.php&quot; id=&quot;myAwesomeDropzone&quot; class=&quot;dropzone&quot;&gt;<br />
  -         &lt;input type=&quot;hidden&quot; name=&quot;path&quot; value=&quot;&lt;?php echo $cur_path?&gt;&quot;/&gt;<br />
  -         &lt;input type=&quot;hidden&quot; name=&quot;path_thumb&quot; value=&quot;&lt;?php echo &quot;thumbs/&quot;.$subdir?&gt;&quot;/&gt;<br />
  -         &lt;div class=&quot;fallback&quot;&gt;<br />
  -             &lt;input name=&quot;file&quot; type=&quot;file&quot; multiple /&gt;<br />
  -         &lt;/div&gt;<br />
  -     &lt;/form&gt;</p>

<p>+ &lt;form action=&quot;dialog.php&quot; method=&quot;post&quot; enctype=&quot;multipart/form-data&quot; id=&quot;myAwesomeDropzone&quot; class=&quot;dropzone&quot;&gt;<br />
  +         &lt;input type=&quot;hidden&quot; name=&quot;path&quot; value=&quot;&lt;?php echo $cur_path?&gt;&quot;/&gt;<br />
  +     &lt;input type=&quot;hidden&quot; name=&quot;path_thumb&quot; value=&quot;&lt;?php echo &quot;thumbs/&quot;.$subdir?&gt;&quot;/&gt;<br />
  +     &lt;div class=&quot;fallback&quot;&gt;<br />
  +         &lt;input name=&quot;file&quot; type=&quot;file&quot; /&gt;<br />
  +            &lt;input type=&quot;submit&quot; name=&quot;submit&quot; value=&quot;plaats&quot; /&gt;<br />
  +     &lt;/div&gt;<br />
  + &lt;/form&gt;</p>

<p>I don't know whether this is the best solution, but it worked for me.</p>

**Comment by trippo** [comment]
thank you this afternoon i try and  change this
