### ISSUE TITLE
Different result image source and tinymce sourcecode

### ISSUE THREAD

**Issue by ghost** [2b3ez/FileManager4TinyMCE#20]
I have project with domain, http://pilihotel.dev
and all files will put in 'http://pilihotel.dev/files'
then admin page editor in 'http://pilihotel.dev/admin'
if edit some post 'http://pilihotel.dev/admin/berita/edit/14'

![1](https://f.cloud.github.com/assets/986173/730077/ddd688f4-e248-11e2-9f89-9feb50147ae3.png)

the problem, when i have selected the image. source on image modal in right path. example 'http://pilihotel.dev/files/avatar.jpg' but when I see in sourcecode tinymce it's change to '../../../files/avatar.jpg'.

![2](https://f.cloud.github.com/assets/986173/730080/e63a8874-e248-11e2-9886-ffcf97017496.png)

any solution?

Sorry bad english.

**Comment by trippo** [comment]
I think tinymce is configured to convert path in relative path
 try to see the config options http://www.tinymce.com/wiki.php/Configuration:relative_urls
