### ISSUE TITLE
file dialog.php: not open tag php

### ISSUE THREAD

**Issue by tanagorns** [2b3ez/FileManager4TinyMCE#21]
https://github.com/2b3ez/FileManager4TinyMCE/blob/master/tinymce/plugins/filemanager/dialog.php#L347

**Comment by ADmad** [comment]
It's actually short open tag :smile:
Still would be better to change it to `<?php` in case short tags are turned off in php config.

**Comment by trippo** [comment]
sorry it's a habit, i fix it
