### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by hervehobbes** [2b3ez/FileManager4TinyMCE#23]
Hello,

I just downloaded your code and when I lanuch it I have :

Parse error: syntax error, unexpected $end  in C:\wamp\www\app\webroot\js\tinymce\plugins\filemanager\dialog.php on line 370

Im' using Php 5.3.5.

Bye

**Comment by trippo** [comment]
Sorry try another time with the new upload version, i think is php short tag. Else reopen the issue

**Comment by hervehobbes** [comment]
yes it solved the problem.
Thanks
