### ISSUE TITLE
Not working for uploading video

### ISSUE THREAD

**Issue by isaumya** [2b3ez/FileManager4TinyMCE#24]
on the upload video poster, when I'm using it to upload a poster, its not working.

Tinymce v4.0.1

**Comment by arndta** [comment]
Can you be more specific?  Is it telling you that the file type is invalid?

**Comment by isaumya** [comment]
Sure, actually, when we uploas a video, for the poster section, it would be a image to select, not a video. I guess. Thats the issue, but it only letting me to select video.

**Comment by trippo** [comment]
In online version do you see the same error?
