### ISSUE TITLE
File not uploading

### ISSUE THREAD

**Issue by isaumya** [2b3ez/FileManager4TinyMCE#28]
In this current version, the file is not uploading at all, it was file till the previous version. File is now even uploading now. I have properly set all the urls. 
Issue:
I upload a new file, it rerfresh the page and keep showing only a single file only.

This is the error log inside filemanager folder. Link: http://txtup.co/gDyev

Try Here:
My app link where the problem is happening: http://html-email.isaumya.com/

Please help...... It's not working anymore....

**Comment by meatpaste** [comment]
um your log has errors in 'utils.php' line 113, line 78 etc. The current version of that file is only 44 lines?

**Comment by arndta** [comment]
In addition, that's a pretty dodgy-looking site.  Sending anonymous emails?

**Comment by isaumya** [comment]
There is nothing dodgy in this site. I have made it google friendly, by following all their privacy policy. Read the Email Removal Terms.
Anyways I have fixed the issue.

**Comment by meatpaste** [comment]
so what was it? your error? you found a bug in the code? its nice to post your experience because it might help others.

**Comment by isaumya** [comment]
Well actually, I re uploaded the new updated version, and after trying for 3-4 times, it started working, I guess, it was some sort of file mismatch at the time of upload.
