### ISSUE TITLE
Secuirity troubles

### ISSUE THREAD

**Issue by autowp** [2b3ez/FileManager4TinyMCE#29]
1. https://github.com/2b3ez/FileManager4TinyMCE/blob/master/tinymce/plugins/filemanager/upload.php#L12 storeFolder used "as is" from POST params. Can be used with "../../.."
2. https://github.com/2b3ez/FileManager4TinyMCE/blob/master/tinymce/plugins/filemanager/force_download.php#L10 
   https://github.com/2b3ez/FileManager4TinyMCE/blob/master/tinymce/plugins/filemanager/delete_folder.php#L11
   https://github.com/2b3ez/FileManager4TinyMCE/blob/master/tinymce/plugins/filemanager/delete_file.php#L11
   https://github.com/2b3ez/FileManager4TinyMCE/blob/master/tinymce/plugins/filemanager/create_folder.php#L11
   Incorrect subdir check. Can be used with "../../../". Must check for "starts with", not "contains".

**Comment by trippo** [comment]
i improve the security in new version
