### ISSUE TITLE
Incompatible with latest TinyMCE version (4.0.2 (2013-07-18))

### ISSUE THREAD

**Issue by marcdebeer** [2b3ez/FileManager4TinyMCE#31]
The file manager doesn't appear to work properly with the latest TinyMCE version (4.0.2 (2013-07-18)). You can still click on the "Insert file" item in the "Insert" menu but then cannot select any files.

The problem however seems to be that the small button beside the image and media dialogs is missing.

**Comment by trippo** [comment]
when you update the version remember to re-follow the instruction, because you miss to copy the plugin.min.js files in media,link image folder inside plugins

**Comment by marcdebeer** [comment]
I did exactly this before posting the ticket and even tried to modify the image plugin. The problem persists. The image plugin code differs from the version in the new TinyMCE. The plugins need to be updated accordingly.

**Comment by trippo** [comment]
I have try the new version at local but i don't have problem, now i'll upload in demo site the new version of tinymce

**Comment by marcdebeer** [comment]
Are you using the jQuery version of TinyMCE? Its possible that I may have skipped a step in between but I doubt it though. I eventually grabbed the 4b script directly from your demo site (non-jquery obviously) and made use of that.

I'll keep an eye out on the demo version and work through the code once its updated.

Thanks for the help.

**Comment by trippo** [comment]
In this new test i use the normal version you can look the js file at http://test.albertoperipolli.com/filemanager4tinymce/js/tinymce/tinymce.min.js

**Comment by trippo** [comment]
can i see you code online?

**Comment by marcdebeer** [comment]
I've replaced all the code with the previous demo version's so I don't have that any more (no commits inbetween so can't checkout between it either). I'll give it another crack using the jQuery version and get back to you. I assume grabbing the master branch should do the trick?

**Comment by emcniece** [comment]
Still broken in tinymce.min.js 4.0.26 (2014-05-06)

**Comment by trippo** [comment]
use responsivefilemananger.com
