### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by henriquetorres** [2b3ez/FileManager4TinyMCE#35]
Edited: Nevermind I figured out that it was my bad!

Hi,

When uploading a file / folder with special char, in server side it is correctly created but in filemanager it displays with encoded char and I'm not able to use that file / folder.
In your demo this does not happen. Any suggestion?

**Comment by trippo** [comment]
i don't know how ... works in my demo ?

**Comment by trippo** [comment]
why you don't use the new amazing version?? www.responsivefilemanager.com

**Comment by henriquetorres** [comment]
Yes, because you have meta tag encoding defined! In my case I didn't notice
that I had a included file that was setting other encoding! :)
No dia Quinta-feira, 8 de Agosto de 2013,
Albertonotifications@github.comescreveu:

> i don't know how ... works in my demo ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/2b3ez/FileManager4TinyMCE/issues/35#issuecomment-22316804
> .

## 

Com os melhores cumprimentos,
Best Regards

 Henrique TorresAdministrador e Gestorhenrique.torres@idealbuys.net

(+351) 961 134 115

info@idealbuys.net

**Comment by henriquetorres** [comment]
I'm using the new amazing version ;)

No dia Quinta-feira, 8 de Agosto de 2013, Henrique
Torreshenrique.torres@idealbuys.net escreveu:

> Yes, because you have meta tag encoding defined! In my case I didn't
> notice that I had a included file that was setting other encoding! :)
> No dia Quinta-feira, 8 de Agosto de 2013, Albertonotifications@github.com<javascript:_e({}, 'cvml', 'Albertonotifications@github.com');>escreveu:
> 
> > i don't know how ... works in my demo ?
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/2b3ez/FileManager4TinyMCE/issues/35#issuecomment-22316804
> > .
> 
> ## 
> 
> Com os melhores cumprimentos,
> Best Regards
> 
>   Henrique TorresAdministrador e Gestor henrique.torres@idealbuys.net<javascript:_e({}, 'cvml', 'henrique.torres@idealbuys.net');>
> 
> (+351) 961 134 115
> 
> info@idealbuys.net <javascript:_e({}, 'cvml', 'info@idealbuys.net');>

## 

Com os melhores cumprimentos,
Best Regards

 Henrique TorresAdministrador e Gestorhenrique.torres@idealbuys.net

(+351) 961 134 115

info@idealbuys.net
