### ISSUE TITLE
PHP_AUTH_USER  error

### ISSUE THREAD

**Issue by vovik64** [2b3ez/FileManager4TinyMCE#37]
got an error when I tried to switch to Java upload Tab

file   filemanager/uploader/index.php  line 79

was 
if($_SERVER['PHP_AUTH_USER'] != '' && $_SERVER['PHP_AUTH_USER'] != '')

must be 
if(isset($_SERVER['PHP_AUTH_USER']) && $_SERVER['PHP_AUTH_USER'] != '')

**Comment by trippo** [comment]
thanks i fix this in next version
