### ISSUE TITLE
lang include vulnerabilities

### ISSUE THREAD

**Issue by vovik64** [2b3ez/FileManager4TinyMCE#38]
maybe I'm wrong (I did not tried to hack it) but it looks little bit weird

file filemanager/execute.php  line 9-13

if (isset($_GET['lang']) && $_GET['lang'] != 'undefined' && is_readable('lang/' . $_GET['lang'] . '.php')) {
    require_once 'lang/' . $_GET['lang'] . '.php';
} else {
    require_once 'lang/en_EN.php';
}

I think need to check $_GET['lang'] more carefully to prevent include custom files "../../../../filename.php"

at least do something like this:

$language_file =  'lang/en_EN.php'; 
if (isset($_GET['lang']) && $_GET['lang'] != 'undefined' && $_GET['lang']!='') {
    $path_parts = pathinfo($_GET['lang']);
    if(is_readable('lang/' .$path_parts['basename']. '.php')){ 
          $language_file =  'lang/' .$path_parts['basename']. '.php';
    }
}
require_once $language_file;
//------------------------------------------------------------------------------------

hope it helps

**Comment by trippo** [comment]
you are right this is an old code part, thanks

**Comment by trippo** [comment]
i change also in the dialog.php
