### ISSUE TITLE
IE 9 windows 7 64bit - List view - sorting doesn´t work

### ISSUE THREAD

**Issue by TomTheRock** [2b3ez/FileManager4TinyMCE#40]
sorting doesn´t work on IE 9

**Comment by trippo** [comment]
I tried with ie 8 and work fine what error give you

**Comment by trippo** [comment]
you must use the new version 7.2 on responsivefilemanager.com

**Comment by TomTheRock** [comment]
after closing complete browser and delete cache it works :)
