### ISSUE TITLE
Tip: Multiple selection of files

### ISSUE THREAD

**Issue by Tomgroot** [2b3ez/FileManager4TinyMCE#43]
Hello Responsive filemanager!

I am enjoying your work! It's a fantastic tool to work with. After you guys, gave the system a stand-alone function I became very enthusiastic! 

Lately I came up with an idea of a multiple selecting function, in order to expand the functionality of the stand-alone function. I mentioned both uploaders already having the function of uploading multiple files, which is obviously great! But using this filemanager in it's stand-alone function, I'm really missing the multiple selecting of files.Maybe a button in the filemanager would bring this functionality. When you click this button the user gets a fucntion to select multiple files. After the user is done selecting, the user can click a submit button in order to send (I don't know how you call it) the multiple files to the webpage. The result then has to be that the chosen files are ligned-up under each other on the webpage(instead of only one file). Maybe to add more functionality to this multiple selection, is that the user not only can send the files to the webpage, but also delete multiple files (or rename or download etc).

I really hope you understand my comment :D and I do really apreciate your work!
I am surely looking forward to this function!

Regards,

Tom Groot

**Comment by trippo** [comment]
I'm developing something like this for version 10

**Comment by henriquetorres** [comment]
Hi trippo, any news on this functionality ?

**Comment by fahjan** [comment]
any news?

**Comment by trippo** [comment]
please use responsivefilemanager.com <http://responsivefilemanager.com/>
