### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by jarodium** [2b3ez/FileManager4TinyMCE#46]
Hello there.

I have a couple of questions.
In Github, you post in the readme.txt that the software is MIT licensed ( http://programmers.stackexchange.com/questions/103273/can-i-use-mit-licence-plugins-in-my-commercial-web-site ) but in the website you state that the software is licensed under a Creative Commons Attribution-NonCommercial 3.0 Unported License.

Which one is it? MIT or CC A-NC?

How much the amount donated would be fair, so that I can use the plugin on commercial websites? And in that case, will I get a license file or document stating i'm allowed to use this in my client's websites?

Thank you. 
PS: This projects rocks!

Regards
Pedro

**Comment by trippo** [comment]
In the readme  there is 

Released under Creative Commons Attribution-NonCommercial 3.0 Unported License.

After a free donation i give you a full commercial license and a customized js file that change the info box on filemanager which change the license type

Regards,
Alberto

Il giorno 15/giu/2014, alle ore 20:01, jarodium notifications@github.com ha scritto:

**Comment by jarodium** [comment]
Thank you.
