### ISSUE TITLE
There is an error! The root folder not exist. 

### ISSUE THREAD

**Issue by simpleann** [2b3ez/FileManager4TinyMCE#48]
I encounter this error:

![image](https://cloud.githubusercontent.com/assets/6926400/3623675/28a65fae-0e52-11e4-89ea-6daec4293b09.png)

TinyMCE is very new to me. and it's hard for me to find the solution on this problem. Would you please help me regarding on this issue?

Thank you.

**Comment by iykeperry** [comment]
Make sure you are referencing your root and upload dir properly.
Go to plugin folder of tinymce open filemanager and open the dialog.php in a file editor, 
at the begining of the body tag, remove the hidden attributes of the input elements, this will help you see a proper directory listing been used and you can adjust your settings at the config.php to suit properly.
Dont forget to revert the dialog.php back to its previous state.
Sorry this is coming late, i just started to implement this recently and had same challenge.
But its been resolved

Hope it helps
Regards

**Comment by atupac** [comment]
Hi iykeperry :)
It's become HARD to either set a free (non-paid) custom filebrowser/uploader plugin nor using existing one => thanks to the awkward documentation and total lack of <!> Working <!> examples for uploading files and getting understandable response (no hate here, just a feedback as CKEditor is doing the same badly things with free plugins like upload widget not functionning...).

So as i had the same "The root folder not exist." error, would you mind up somewhere your needed work ?   By the way All i need si to upload a file (image, video, link-file) to mysql server db, and get in return from my php script the url of file... Can you upload here the code on php-server side you used  ? thanks.

**Comment by TomTheRock** [comment]
my responsivefilemanager root: /admin/ResponsiveFilemanager/filemanager/config/config.php
my files root: /_upload_bilder/_filemanager/
my tinymce: /admin/tinymce/js/tinymce/

These are my config:

$base_url = 'http://'.$_SERVER['HTTP_HOST'];  // base url (only domain) of site (without final /). If you prefer relative urls leave empty
$upload_dir = '/source/'; // path from base_url to base of upload folder (with start and final /)
$current_path = '../source/'; // relative path from filemanager folder to upload folder (with final /)
//thumbs folder can't put inside upload folder
$thumbs_base_path = '../thumbs/'; // relative path from filemanager folder to thumbs folder (with final /)

$root = rtrim($_SERVER['DOCUMENT_ROOT'],'/'); // don't touch this parameter
$base_url="";  // base url of site (without final /). If you prefer relative urls leave empty
$upload_dir = '/'; // path from base_url to base of upload folder (with start and final /)
$current_path = '../../../'; // relative path from filemanager folder to upload folder (with final /)

**Comment by atupac** [comment]
forget it, i 'll switch to summernote, a lot clearer and efficient...

**Comment by trippo** [comment]
please use http://responsivefilemanager.com

**Comment by wangai** [comment]
Incase someone stumbles on this like I did
these settings worked for me

the url for my project is set up like this
http://127.0.0.1/project/branch/public/


$base_url = "";
$upload_dir = "/project/branch/public/path/to/tinymce/upload_dir/";
$current_path = "/../../upload_dir/";

make sure you follow setup instructions in this repo
